import { Link, useRouter } from "@tanstack/react-router";
import { useState } from "react";
import { Archive, ArrowLeft, CreditCard, History, RotateCcw } from "lucide-react";
import { toast } from "sonner";
import { Button } from "~/components/ui/button";
import { Input } from "~/components/ui/input";
import { Textarea } from "~/components/ui/textarea";
import { retryNotification, setRequestArchived, transitionRequest, verifyPayment } from "../requests.mutations";
import { STATUS_LABELS, TRANSITIONS, subjectFromFormData, type RequirementReviewStatus, type RequestStatus } from "../requests.types";

export function RequestDetailPage({data}:{data:any}){
  const router=useRouter(); const request=data.request; const status=request.status as RequestStatus;
  const [reason,setReason]=useState(""); const [receipt,setReceipt]=useState(""); const [busy,setBusy]=useState(false);
  const [reviews,setReviews]=useState<Record<string,RequirementReviewStatus>>(()=>Object.fromEntries(data.requirements.map((item:any)=>[item.id,item.review_status])));
  const cashier=data.role==="cashier"; const canApprove=data.permissions.includes("requests:approve"); const canRelease=data.permissions.includes("requests:release");
  const transitions=TRANSITIONS[status].filter((item)=>item.status!=="ready_for_release"||canApprove).filter((item)=>item.status!=="released"||canRelease);
  const run=async(action:()=>Promise<unknown>)=>{setBusy(true);try{await action();toast.success("Request updated");await router.invalidate()}catch(error){toast.error(error instanceof Error?error.message:"Update failed")}finally{setBusy(false)}};
  const requester=data.contact?.requester_name ?? (`${data.applicant?.first_name??""} ${data.applicant?.last_name??""}`.trim() || "Registered applicant");
  return <div className="dashboard-page max-w-6xl space-y-5">
    <Link to="/requests" className="inline-flex items-center gap-2 text-sm font-semibold text-primary"><ArrowLeft className="size-4"/>Back to queue</Link>
    <header className="dashboard-hero"><div className="relative z-10"><div className="flex flex-wrap items-center gap-3"><h1 className="font-mono text-2xl font-extrabold text-white">{request.tracking_number}</h1><span className="rounded-md bg-white/15 px-2 py-1 text-xs font-semibold text-white">{STATUS_LABELS[status]}</span></div><p className="mt-2 text-white/75">{data.service?.name??request.request_type} · {data.department?.name??"Unassigned"}</p></div></header>
    <div className="grid gap-5 lg:grid-cols-[1fr_340px]">
      <main className="space-y-5">
        <Panel title="Request details"><dl className="grid gap-4 text-sm sm:grid-cols-2"><Info label="Requester" value={requester}/><Info label="Document subject" value={subjectFromFormData(request.form_data)}/><Info label="Submission" value={request.submission_source==="walk_in"?"Walk-in":"Online"}/><Info label="Submitted" value={new Date(request.created_at).toLocaleString()}/><Info label="Fee" value={`₱${Number(request.fees_due??0).toFixed(2)}`}/><Info label="Payment" value={request.payment_status??"unpaid"}/></dl></Panel>
        {!cashier?<><Panel title="Submitted information"><dl className="grid gap-3 text-sm sm:grid-cols-2">{Object.entries(request.form_data??{}).map(([key,value])=><Info key={key} label={key.replaceAll("_"," ")} value={String(value)}/>)}</dl></Panel>
        <Panel title="Requirement review"><div className="space-y-3">{data.requirements.map((item:any)=><div key={item.id} className="grid gap-2 rounded-lg border p-3 sm:grid-cols-[1fr_180px]"><div><p className="text-sm font-semibold">{item.requirement_name}</p><p className="text-xs text-muted-foreground">{item.is_mandatory?"Mandatory":"If applicable"}</p></div><select className="h-9 rounded-md border bg-white px-2 text-sm" value={reviews[item.id]} disabled={busy||!["under_validation","incomplete"].includes(status)} onChange={(event)=>setReviews((old)=>({...old,[item.id]:event.target.value as RequirementReviewStatus}))}><option value="pending">Pending</option><option value="accepted">Accepted</option><option value="missing">Missing</option>{!item.is_mandatory?<option value="not_applicable">Not applicable</option>:null}</select></div>)}</div></Panel></>:null}
        <Panel title="Activity"><div className="space-y-4">{data.activity.length?data.activity.map((item:any)=><div key={item.id} className="flex gap-3 text-sm"><History className="mt-0.5 size-4 shrink-0 text-primary"/><div><p className="font-semibold capitalize">{item.event_type.replaceAll("_"," ")}</p><p className="text-xs text-muted-foreground">{item.actorName} · {new Date(item.created_at).toLocaleString()}</p>{item.reason?<p className="mt-1 text-muted-foreground">{item.reason}</p>:null}</div></div>):<p className="text-sm text-muted-foreground">No activity recorded.</p>}</div></Panel>
      </main>
      <aside className="space-y-5">
        {cashier||data.permissions.includes("requests:collect_payment")?<Panel title="Payment verification"><p className="mb-3 text-sm text-muted-foreground">Available only when the request is ready for release.</p><Input value={receipt} onChange={(e)=>setReceipt(e.target.value)} placeholder="Official receipt / reference"/><Button className="mt-3 w-full" disabled={busy||status!=="ready_for_release"||request.payment_status==="verified"} onClick={()=>run(()=>verifyPayment({data:{requestId:request.id,expectedVersion:request.workflow_version,reference:receipt}}))}><CreditCard className="size-4"/>Verify payment</Button>{request.payment_reference?<p className="mt-3 text-xs">Receipt: <strong>{request.payment_reference}</strong></p>:null}</Panel>:null}
        {!cashier&&transitions.length?<Panel title="Workflow actions"><Textarea value={reason} onChange={(e)=>setReason(e.target.value)} placeholder="Reason (required for incomplete, rejection, or return)"/><div className="mt-3 grid gap-2">{transitions.map((transition)=><Button key={transition.status} variant={transition.status==="rejected"?"destructive":"default"} disabled={busy||(transition.reason&&!reason.trim())} onClick={()=>run(()=>transitionRequest({data:{requestId:request.id,expectedVersion:request.workflow_version,newStatus:transition.status,reason:reason||undefined,reviews:["under_validation","incomplete"].includes(status)?Object.entries(reviews).map(([id,value])=>({id,status:value})):undefined}}))}>{transition.label}</Button>)}</div></Panel>:null}
        {data.role==="admin"&&(["released","rejected"].includes(status)||request.archived_at)?<Panel title="Archive"><Button variant="outline" className="w-full" disabled={busy} onClick={()=>run(()=>setRequestArchived({data:{requestId:request.id,expectedVersion:request.workflow_version,restore:Boolean(request.archived_at)}}))}>{request.archived_at?<><RotateCcw className="size-4"/>Restore request</>:<><Archive className="size-4"/>Archive request</>}</Button></Panel>:null}
        {data.permissions.includes("requests:retry_notification")&&data.notifications.some((item:any)=>item.email_status==="failed")?<Panel title="Email delivery"><div className="space-y-3">{data.notifications.filter((item:any)=>item.email_status==="failed").map((item:any)=><div key={item.id} className="rounded-lg border border-destructive/20 bg-destructive/5 p-3"><p className="text-sm font-semibold">{item.title}</p><p className="mt-1 text-xs text-muted-foreground">{item.email_last_error}</p><Button size="sm" variant="outline" className="mt-3" disabled={busy} onClick={()=>run(()=>retryNotification({data:item.id}))}><RotateCcw className="size-4"/>Retry email</Button></div>)}</div></Panel>:null}
      </aside>
    </div>
  </div>
}
function Panel({title,children}:{title:string;children:React.ReactNode}){return <section className="dashboard-panel overflow-hidden"><h2 className="border-b px-5 py-4 font-bold">{title}</h2><div className="p-5">{children}</div></section>}
function Info({label,value}:{label:string;value:string}){return <div><dt className="text-xs font-bold uppercase tracking-wide text-muted-foreground">{label}</dt><dd className="mt-1 font-medium capitalize">{value||"Not provided"}</dd></div>}
