// Falls back to a title-cased version of the raw value (e.g. "payment_verified"
// -> "Payment Verified") instead of the snake_case enum, so a status the switch
// below hasn't been taught yet degrades gracefully instead of leaking an id.
function titleCaseStatus(value: string) {
  return value
    .split("_")
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
    .join(" ");
}

type StatusBadgeVariant = "info" | "success" | "warning" | "neutral" | "destructive";

interface StatusDetails {
  label: string;
  styles: string;
  dot: string;
  variant: StatusBadgeVariant;
}

// The timeline keeps past steps gray; only the step the request is in right
// now is tinted, so the color itself answers "where is my request?".
export function getCurrentDotClass(variant: StatusBadgeVariant) {
  switch (variant) {
    case "info":
      return "bg-health-info-dot";
    case "success":
      return "bg-health-success-dot";
    case "warning":
      return "bg-health-warning-dot";
    case "destructive":
      return "bg-health-error-dot";
    default:
      return "bg-health-neutral-dot";
  }
}

const APPLICANT_NOTES: Record<string, string> = {
  submitted: "Request submitted online.",
  under_validation: "Staff are reviewing your requirements.",
  incomplete:
    "Some requirements are missing or need correction. Please check the details and submit what's needed.",
  rejected: "Your request could not be accepted.",
  processing: "Your requirements are complete. Staff are preparing your record.",
  ready_for_release: "Your document is ready. Pay at the CCRO cashier and claim it.",
  released: "Payment verified and your document has been released.",
};

const STAFF_NOTES: Record<string, string> = {
  submitted: "Request submitted.",
  under_validation: "Validation started. Requirements are being reviewed.",
  incomplete: "Marked incomplete. Applicant needs to provide missing requirements.",
  rejected: "Request rejected.",
  processing: "Requirements validated. Record is being prepared.",
  ready_for_release: "Record prepared. Awaiting payment verification.",
  released: "Payment verified. Document released to the applicant.",
};

// Remark to show for a log entry. A remark staff typed is shown as-is; an
// empty or auto-generated one (the generic "Advanced from…", or an applicant
// note saved by an earlier version) is replaced by a descriptive note. The
// wording depends on who is reading: applicants are addressed directly, staff
// get a neutral third-person log.
// Free services (fee of 0) have no payment step to mention.
const APPLICANT_READY_FREE =
  "Your document is ready. No fee is due — show your transaction number at the CCRO cashier to confirm, then claim it.";
const STAFF_READY_FREE = "Record prepared. No fee due — awaiting cashier confirmation.";
const LEGACY_APPLICANT_READY_FREE =
  "Your document is ready. No payment is needed — claim it at the CCRO.";

export function getLogNote(
  status: string | null,
  remarks: string | null,
  audience: "applicant" | "staff",
  feesDue = 0,
): string | null {
  const isAutoGenerated =
    !remarks ||
    remarks.startsWith("Advanced from") ||
    remarks === APPLICANT_READY_FREE ||
    remarks === LEGACY_APPLICANT_READY_FREE ||
    Object.values(APPLICANT_NOTES).includes(remarks);
  if (!isAutoGenerated) return remarks;
  if (status === "ready_for_release" && feesDue <= 0) {
    return audience === "staff" ? STAFF_READY_FREE : APPLICANT_READY_FREE;
  }
  if (status === "released" && feesDue <= 0) {
    return audience === "staff"
      ? "Cashier confirmed no fee. Document released to the applicant."
      : "The cashier confirmed no fee is due and your document has been released.";
  }
  const notes = audience === "staff" ? STAFF_NOTES : APPLICANT_NOTES;
  return (status && notes[status]) || remarks;
}

interface PaymentDetails {
  label: string;
  styles: string;
  variant: StatusBadgeVariant;
}

// Timeline dots deliberately use a narrower palette than the status badges:
// gray for ordinary forward progress, red only for the states that need
// attention, green only for the one true finish line. Mirroring the badges'
// full 5-tone palette down a list of log entries reads as noise, not signal.
export function getStatusDetails(status: string | null): StatusDetails {
  switch (status) {
    case "submitted":
      return { label: "Submitted", styles: "status-neutral", dot: "bg-health-neutral-dot", variant: "neutral" };
    case "under_validation":
      return { label: "Under Validation", styles: "status-info", dot: "bg-health-neutral-dot", variant: "info" };
    case "incomplete":
      return { label: "Incomplete", styles: "status-warning", dot: "bg-health-neutral-dot", variant: "warning" };
    case "rejected":
      return { label: "Rejected", styles: "status-error", dot: "bg-health-error-dot", variant: "destructive" };
    case "processing":
      return { label: "Processing", styles: "status-info", dot: "bg-health-neutral-dot", variant: "info" };
    case "ready_for_release":
      return { label: "Ready for Release", styles: "status-success", dot: "bg-health-neutral-dot", variant: "success" };
    case "released":
      return { label: "Released", styles: "status-success", dot: "bg-health-success-dot", variant: "success" };
    case "document_approved":
      return { label: "Document Approved", styles: "status-success", dot: "bg-health-neutral-dot", variant: "success" };
    case "document_rejected":
      return { label: "Document Rejected", styles: "status-error", dot: "bg-health-error-dot", variant: "destructive" };
    case "document_resubmitted":
      return { label: "Document Resubmitted", styles: "status-warning", dot: "bg-health-neutral-dot", variant: "warning" };
    case "payment_verified":
      return { label: "Payment Verified", styles: "status-success", dot: "bg-health-neutral-dot", variant: "success" };
    case "document_reverted":
      return { label: "Document Reopened", styles: "status-warning", dot: "bg-health-neutral-dot", variant: "warning" };
    default:
      return {
        label: status ? titleCaseStatus(status) : "Unknown",
        styles: "status-neutral",
        dot: "bg-health-neutral-dot",
        variant: "neutral",
      };
  }
}

export function getPaymentDetails(paymentStatus: string | null): PaymentDetails {
  switch (paymentStatus) {
    case "unpaid":
      return { label: "Unpaid", styles: "status-warning", variant: "warning" };
    case "verified":
      return { label: "Paid", styles: "status-success", variant: "success" };
    default:
      return { label: paymentStatus || "Unpaid", styles: "status-neutral", variant: "neutral" };
  }
}
