/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RequirementsRouteImport } from './routes/requirements'
import { Route as LogoutRouteImport } from './routes/logout'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AcceptInvitationRouteImport } from './routes/accept-invitation'
import { Route as AuthedRouteRouteImport } from './routes/_authed/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as AuthedStaffDashboardRouteImport } from './routes/_authed/staff-dashboard'
import { Route as AuthedRequestsRouteImport } from './routes/_authed/requests'
import { Route as AuthedNotificationsRouteImport } from './routes/_authed/notifications'
import { Route as AuthedMyRequestsRouteImport } from './routes/_authed/my-requests'
import { Route as AuthedDashboardRouteImport } from './routes/_authed/dashboard'
import { Route as AuthedRequestsNewRouteImport } from './routes/_authed/requests.new'
import { Route as AuthedRequestsRequestIdRouteImport } from './routes/_authed/requests.$requestId'
import { Route as AuthedAdminStaffRouteImport } from './routes/_authed/admin/staff'
import { Route as AuthedAdminServicesRouteImport } from './routes/_authed/admin/services'
import { Route as AuthedserviceServicesRouteImport } from './routes/_authed/(service)/services'
import { Route as AuthedserviceServiceServiceCodeRouteImport } from './routes/_authed/(service)/service.$serviceCode'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RequirementsRoute = RequirementsRouteImport.update({
  id: '/requirements',
  path: '/requirements',
  getParentRoute: () => rootRouteImport,
} as any)
const LogoutRoute = LogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptInvitationRoute = AcceptInvitationRouteImport.update({
  id: '/accept-invitation',
  path: '/accept-invitation',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRouteRoute = AuthedRouteRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedStaffDashboardRoute = AuthedStaffDashboardRouteImport.update({
  id: '/staff-dashboard',
  path: '/staff-dashboard',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedRequestsRoute = AuthedRequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedNotificationsRoute = AuthedNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedMyRequestsRoute = AuthedMyRequestsRouteImport.update({
  id: '/my-requests',
  path: '/my-requests',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedDashboardRoute = AuthedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedRequestsNewRoute = AuthedRequestsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthedRequestsRoute,
} as any)
const AuthedRequestsRequestIdRoute = AuthedRequestsRequestIdRouteImport.update({
  id: '/$requestId',
  path: '/$requestId',
  getParentRoute: () => AuthedRequestsRoute,
} as any)
const AuthedAdminStaffRoute = AuthedAdminStaffRouteImport.update({
  id: '/admin/staff',
  path: '/admin/staff',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedAdminServicesRoute = AuthedAdminServicesRouteImport.update({
  id: '/admin/services',
  path: '/admin/services',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedserviceServicesRoute = AuthedserviceServicesRouteImport.update({
  id: '/(service)/services',
  path: '/services',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedserviceServiceServiceCodeRoute =
  AuthedserviceServiceServiceCodeRouteImport.update({
    id: '/(service)/service/$serviceCode',
    path: '/service/$serviceCode',
    getParentRoute: () => AuthedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accept-invitation': typeof AcceptInvitationRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/requirements': typeof RequirementsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/my-requests': typeof AuthedMyRequestsRoute
  '/notifications': typeof AuthedNotificationsRoute
  '/requests': typeof AuthedRequestsRouteWithChildren
  '/staff-dashboard': typeof AuthedStaffDashboardRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/services': typeof AuthedserviceServicesRoute
  '/admin/services': typeof AuthedAdminServicesRoute
  '/admin/staff': typeof AuthedAdminStaffRoute
  '/requests/$requestId': typeof AuthedRequestsRequestIdRoute
  '/requests/new': typeof AuthedRequestsNewRoute
  '/service/$serviceCode': typeof AuthedserviceServiceServiceCodeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accept-invitation': typeof AcceptInvitationRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/requirements': typeof RequirementsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/my-requests': typeof AuthedMyRequestsRoute
  '/notifications': typeof AuthedNotificationsRoute
  '/requests': typeof AuthedRequestsRouteWithChildren
  '/staff-dashboard': typeof AuthedStaffDashboardRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/services': typeof AuthedserviceServicesRoute
  '/admin/services': typeof AuthedAdminServicesRoute
  '/admin/staff': typeof AuthedAdminStaffRoute
  '/requests/$requestId': typeof AuthedRequestsRequestIdRoute
  '/requests/new': typeof AuthedRequestsNewRoute
  '/service/$serviceCode': typeof AuthedserviceServiceServiceCodeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteRouteWithChildren
  '/accept-invitation': typeof AcceptInvitationRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/requirements': typeof RequirementsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_authed/dashboard': typeof AuthedDashboardRoute
  '/_authed/my-requests': typeof AuthedMyRequestsRoute
  '/_authed/notifications': typeof AuthedNotificationsRoute
  '/_authed/requests': typeof AuthedRequestsRouteWithChildren
  '/_authed/staff-dashboard': typeof AuthedStaffDashboardRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/_authed/(service)/services': typeof AuthedserviceServicesRoute
  '/_authed/admin/services': typeof AuthedAdminServicesRoute
  '/_authed/admin/staff': typeof AuthedAdminStaffRoute
  '/_authed/requests/$requestId': typeof AuthedRequestsRequestIdRoute
  '/_authed/requests/new': typeof AuthedRequestsNewRoute
  '/_authed/(service)/service/$serviceCode': typeof AuthedserviceServiceServiceCodeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accept-invitation'
    | '/forgot-password'
    | '/login'
    | '/logout'
    | '/requirements'
    | '/reset-password'
    | '/signup'
    | '/dashboard'
    | '/my-requests'
    | '/notifications'
    | '/requests'
    | '/staff-dashboard'
    | '/auth/callback'
    | '/services'
    | '/admin/services'
    | '/admin/staff'
    | '/requests/$requestId'
    | '/requests/new'
    | '/service/$serviceCode'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accept-invitation'
    | '/forgot-password'
    | '/login'
    | '/logout'
    | '/requirements'
    | '/reset-password'
    | '/signup'
    | '/dashboard'
    | '/my-requests'
    | '/notifications'
    | '/requests'
    | '/staff-dashboard'
    | '/auth/callback'
    | '/services'
    | '/admin/services'
    | '/admin/staff'
    | '/requests/$requestId'
    | '/requests/new'
    | '/service/$serviceCode'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/accept-invitation'
    | '/forgot-password'
    | '/login'
    | '/logout'
    | '/requirements'
    | '/reset-password'
    | '/signup'
    | '/_authed/dashboard'
    | '/_authed/my-requests'
    | '/_authed/notifications'
    | '/_authed/requests'
    | '/_authed/staff-dashboard'
    | '/auth/callback'
    | '/_authed/(service)/services'
    | '/_authed/admin/services'
    | '/_authed/admin/staff'
    | '/_authed/requests/$requestId'
    | '/_authed/requests/new'
    | '/_authed/(service)/service/$serviceCode'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRouteRoute: typeof AuthedRouteRouteWithChildren
  AcceptInvitationRoute: typeof AcceptInvitationRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  LogoutRoute: typeof LogoutRoute
  RequirementsRoute: typeof RequirementsRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/requirements': {
      id: '/requirements'
      path: '/requirements'
      fullPath: '/requirements'
      preLoaderRoute: typeof RequirementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accept-invitation': {
      id: '/accept-invitation'
      path: '/accept-invitation'
      fullPath: '/accept-invitation'
      preLoaderRoute: typeof AcceptInvitationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/staff-dashboard': {
      id: '/_authed/staff-dashboard'
      path: '/staff-dashboard'
      fullPath: '/staff-dashboard'
      preLoaderRoute: typeof AuthedStaffDashboardRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/requests': {
      id: '/_authed/requests'
      path: '/requests'
      fullPath: '/requests'
      preLoaderRoute: typeof AuthedRequestsRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/notifications': {
      id: '/_authed/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthedNotificationsRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/my-requests': {
      id: '/_authed/my-requests'
      path: '/my-requests'
      fullPath: '/my-requests'
      preLoaderRoute: typeof AuthedMyRequestsRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/dashboard': {
      id: '/_authed/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthedDashboardRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/requests/new': {
      id: '/_authed/requests/new'
      path: '/new'
      fullPath: '/requests/new'
      preLoaderRoute: typeof AuthedRequestsNewRouteImport
      parentRoute: typeof AuthedRequestsRoute
    }
    '/_authed/requests/$requestId': {
      id: '/_authed/requests/$requestId'
      path: '/$requestId'
      fullPath: '/requests/$requestId'
      preLoaderRoute: typeof AuthedRequestsRequestIdRouteImport
      parentRoute: typeof AuthedRequestsRoute
    }
    '/_authed/admin/staff': {
      id: '/_authed/admin/staff'
      path: '/admin/staff'
      fullPath: '/admin/staff'
      preLoaderRoute: typeof AuthedAdminStaffRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/admin/services': {
      id: '/_authed/admin/services'
      path: '/admin/services'
      fullPath: '/admin/services'
      preLoaderRoute: typeof AuthedAdminServicesRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/(service)/services': {
      id: '/_authed/(service)/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof AuthedserviceServicesRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/(service)/service/$serviceCode': {
      id: '/_authed/(service)/service/$serviceCode'
      path: '/service/$serviceCode'
      fullPath: '/service/$serviceCode'
      preLoaderRoute: typeof AuthedserviceServiceServiceCodeRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
  }
}

interface AuthedRequestsRouteChildren {
  AuthedRequestsRequestIdRoute: typeof AuthedRequestsRequestIdRoute
  AuthedRequestsNewRoute: typeof AuthedRequestsNewRoute
}

const AuthedRequestsRouteChildren: AuthedRequestsRouteChildren = {
  AuthedRequestsRequestIdRoute: AuthedRequestsRequestIdRoute,
  AuthedRequestsNewRoute: AuthedRequestsNewRoute,
}

const AuthedRequestsRouteWithChildren = AuthedRequestsRoute._addFileChildren(
  AuthedRequestsRouteChildren,
)

interface AuthedRouteRouteChildren {
  AuthedDashboardRoute: typeof AuthedDashboardRoute
  AuthedMyRequestsRoute: typeof AuthedMyRequestsRoute
  AuthedNotificationsRoute: typeof AuthedNotificationsRoute
  AuthedRequestsRoute: typeof AuthedRequestsRouteWithChildren
  AuthedStaffDashboardRoute: typeof AuthedStaffDashboardRoute
  AuthedserviceServicesRoute: typeof AuthedserviceServicesRoute
  AuthedAdminServicesRoute: typeof AuthedAdminServicesRoute
  AuthedAdminStaffRoute: typeof AuthedAdminStaffRoute
  AuthedserviceServiceServiceCodeRoute: typeof AuthedserviceServiceServiceCodeRoute
}

const AuthedRouteRouteChildren: AuthedRouteRouteChildren = {
  AuthedDashboardRoute: AuthedDashboardRoute,
  AuthedMyRequestsRoute: AuthedMyRequestsRoute,
  AuthedNotificationsRoute: AuthedNotificationsRoute,
  AuthedRequestsRoute: AuthedRequestsRouteWithChildren,
  AuthedStaffDashboardRoute: AuthedStaffDashboardRoute,
  AuthedserviceServicesRoute: AuthedserviceServicesRoute,
  AuthedAdminServicesRoute: AuthedAdminServicesRoute,
  AuthedAdminStaffRoute: AuthedAdminStaffRoute,
  AuthedserviceServiceServiceCodeRoute: AuthedserviceServiceServiceCodeRoute,
}

const AuthedRouteRouteWithChildren = AuthedRouteRoute._addFileChildren(
  AuthedRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRouteRoute: AuthedRouteRouteWithChildren,
  AcceptInvitationRoute: AcceptInvitationRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  LogoutRoute: LogoutRoute,
  RequirementsRoute: RequirementsRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  AuthCallbackRoute: AuthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
