/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrackRouteImport } from './routes/track'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RequirementsRouteImport } from './routes/requirements'
import { Route as LogoutRouteImport } from './routes/logout'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AcceptInvitationRouteImport } from './routes/accept-invitation'
import { Route as AuthedRouteRouteImport } from './routes/_authed/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApplyIndexRouteImport } from './routes/apply/index'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as AuthedStaffDashboardRouteImport } from './routes/_authed/staff-dashboard'
import { Route as AuthedPaymentHistoryRouteImport } from './routes/_authed/payment-history'
import { Route as AuthedMyRequestsRouteImport } from './routes/_authed/my-requests'
import { Route as AuthedDashboardRouteImport } from './routes/_authed/dashboard'
import { Route as AuthedCashierRouteImport } from './routes/_authed/cashier'
import { Route as ApplyServiceCodeRouteRouteImport } from './routes/apply/$serviceCode/route'
import { Route as ApplyServiceCodeIndexRouteImport } from './routes/apply/$serviceCode/index'
import { Route as AuthedRequestsIndexRouteImport } from './routes/_authed/requests/index'
import { Route as AuthedAdminIndexRouteImport } from './routes/_authed/admin/index'
import { Route as ApplyServiceCodeReviewRouteImport } from './routes/apply/$serviceCode/review'
import { Route as ApplyServiceCodeDocumentsRouteImport } from './routes/apply/$serviceCode/documents'
import { Route as ApplyServiceCodeDetailsRouteImport } from './routes/apply/$serviceCode/details'
import { Route as ApplyServiceCodeCaseRouteImport } from './routes/apply/$serviceCode/case'
import { Route as AuthedSystemAdminSecurityRouteImport } from './routes/_authed/system-admin/security'
import { Route as AuthedSystemAdminHealthRouteImport } from './routes/_authed/system-admin/health'
import { Route as AuthedSystemAdminAuditRouteImport } from './routes/_authed/system-admin/audit'
import { Route as AuthedSystemAdminAccountsRouteImport } from './routes/_authed/system-admin/accounts'
import { Route as AuthedRequestsRequestIdRouteImport } from './routes/_authed/requests/$requestId'
import { Route as AuthedAdminStaffRouteImport } from './routes/_authed/admin/staff'
import { Route as AuthedAdminServicesRouteImport } from './routes/_authed/admin/services'
import { Route as AuthedAdminReportsRouteImport } from './routes/_authed/admin/reports'
import { Route as AuthedserviceServicesRouteImport } from './routes/_authed/(service)/services'
import { Route as AuthedserviceServiceServiceCodeRouteImport } from './routes/_authed/(service)/service.$serviceCode'

const TrackRoute = TrackRouteImport.update({
  id: '/track',
  path: '/track',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RequirementsRoute = RequirementsRouteImport.update({
  id: '/requirements',
  path: '/requirements',
  getParentRoute: () => rootRouteImport,
} as any)
const LogoutRoute = LogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptInvitationRoute = AcceptInvitationRouteImport.update({
  id: '/accept-invitation',
  path: '/accept-invitation',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRouteRoute = AuthedRouteRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplyIndexRoute = ApplyIndexRouteImport.update({
  id: '/apply/',
  path: '/apply/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedStaffDashboardRoute = AuthedStaffDashboardRouteImport.update({
  id: '/staff-dashboard',
  path: '/staff-dashboard',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedPaymentHistoryRoute = AuthedPaymentHistoryRouteImport.update({
  id: '/payment-history',
  path: '/payment-history',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedMyRequestsRoute = AuthedMyRequestsRouteImport.update({
  id: '/my-requests',
  path: '/my-requests',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedDashboardRoute = AuthedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedCashierRoute = AuthedCashierRouteImport.update({
  id: '/cashier',
  path: '/cashier',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const ApplyServiceCodeRouteRoute = ApplyServiceCodeRouteRouteImport.update({
  id: '/apply/$serviceCode',
  path: '/apply/$serviceCode',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplyServiceCodeIndexRoute = ApplyServiceCodeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ApplyServiceCodeRouteRoute,
} as any)
const AuthedRequestsIndexRoute = AuthedRequestsIndexRouteImport.update({
  id: '/requests/',
  path: '/requests/',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedAdminIndexRoute = AuthedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const ApplyServiceCodeReviewRoute = ApplyServiceCodeReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => ApplyServiceCodeRouteRoute,
} as any)
const ApplyServiceCodeDocumentsRoute =
  ApplyServiceCodeDocumentsRouteImport.update({
    id: '/documents',
    path: '/documents',
    getParentRoute: () => ApplyServiceCodeRouteRoute,
  } as any)
const ApplyServiceCodeDetailsRoute = ApplyServiceCodeDetailsRouteImport.update({
  id: '/details',
  path: '/details',
  getParentRoute: () => ApplyServiceCodeRouteRoute,
} as any)
const ApplyServiceCodeCaseRoute = ApplyServiceCodeCaseRouteImport.update({
  id: '/case',
  path: '/case',
  getParentRoute: () => ApplyServiceCodeRouteRoute,
} as any)
const AuthedSystemAdminSecurityRoute =
  AuthedSystemAdminSecurityRouteImport.update({
    id: '/system-admin/security',
    path: '/system-admin/security',
    getParentRoute: () => AuthedRouteRoute,
  } as any)
const AuthedSystemAdminHealthRoute = AuthedSystemAdminHealthRouteImport.update({
  id: '/system-admin/health',
  path: '/system-admin/health',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedSystemAdminAuditRoute = AuthedSystemAdminAuditRouteImport.update({
  id: '/system-admin/audit',
  path: '/system-admin/audit',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedSystemAdminAccountsRoute =
  AuthedSystemAdminAccountsRouteImport.update({
    id: '/system-admin/accounts',
    path: '/system-admin/accounts',
    getParentRoute: () => AuthedRouteRoute,
  } as any)
const AuthedRequestsRequestIdRoute = AuthedRequestsRequestIdRouteImport.update({
  id: '/requests/$requestId',
  path: '/requests/$requestId',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedAdminStaffRoute = AuthedAdminStaffRouteImport.update({
  id: '/admin/staff',
  path: '/admin/staff',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedAdminServicesRoute = AuthedAdminServicesRouteImport.update({
  id: '/admin/services',
  path: '/admin/services',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedAdminReportsRoute = AuthedAdminReportsRouteImport.update({
  id: '/admin/reports',
  path: '/admin/reports',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedserviceServicesRoute = AuthedserviceServicesRouteImport.update({
  id: '/(service)/services',
  path: '/services',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedserviceServiceServiceCodeRoute =
  AuthedserviceServiceServiceCodeRouteImport.update({
    id: '/(service)/service/$serviceCode',
    path: '/service/$serviceCode',
    getParentRoute: () => AuthedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accept-invitation': typeof AcceptInvitationRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/requirements': typeof RequirementsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/track': typeof TrackRoute
  '/apply/$serviceCode': typeof ApplyServiceCodeRouteRouteWithChildren
  '/cashier': typeof AuthedCashierRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/my-requests': typeof AuthedMyRequestsRoute
  '/payment-history': typeof AuthedPaymentHistoryRoute
  '/staff-dashboard': typeof AuthedStaffDashboardRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/apply/': typeof ApplyIndexRoute
  '/services': typeof AuthedserviceServicesRoute
  '/admin/reports': typeof AuthedAdminReportsRoute
  '/admin/services': typeof AuthedAdminServicesRoute
  '/admin/staff': typeof AuthedAdminStaffRoute
  '/requests/$requestId': typeof AuthedRequestsRequestIdRoute
  '/system-admin/accounts': typeof AuthedSystemAdminAccountsRoute
  '/system-admin/audit': typeof AuthedSystemAdminAuditRoute
  '/system-admin/health': typeof AuthedSystemAdminHealthRoute
  '/system-admin/security': typeof AuthedSystemAdminSecurityRoute
  '/apply/$serviceCode/case': typeof ApplyServiceCodeCaseRoute
  '/apply/$serviceCode/details': typeof ApplyServiceCodeDetailsRoute
  '/apply/$serviceCode/documents': typeof ApplyServiceCodeDocumentsRoute
  '/apply/$serviceCode/review': typeof ApplyServiceCodeReviewRoute
  '/admin/': typeof AuthedAdminIndexRoute
  '/requests/': typeof AuthedRequestsIndexRoute
  '/apply/$serviceCode/': typeof ApplyServiceCodeIndexRoute
  '/service/$serviceCode': typeof AuthedserviceServiceServiceCodeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accept-invitation': typeof AcceptInvitationRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/requirements': typeof RequirementsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/track': typeof TrackRoute
  '/cashier': typeof AuthedCashierRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/my-requests': typeof AuthedMyRequestsRoute
  '/payment-history': typeof AuthedPaymentHistoryRoute
  '/staff-dashboard': typeof AuthedStaffDashboardRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/apply': typeof ApplyIndexRoute
  '/services': typeof AuthedserviceServicesRoute
  '/admin/reports': typeof AuthedAdminReportsRoute
  '/admin/services': typeof AuthedAdminServicesRoute
  '/admin/staff': typeof AuthedAdminStaffRoute
  '/requests/$requestId': typeof AuthedRequestsRequestIdRoute
  '/system-admin/accounts': typeof AuthedSystemAdminAccountsRoute
  '/system-admin/audit': typeof AuthedSystemAdminAuditRoute
  '/system-admin/health': typeof AuthedSystemAdminHealthRoute
  '/system-admin/security': typeof AuthedSystemAdminSecurityRoute
  '/apply/$serviceCode/case': typeof ApplyServiceCodeCaseRoute
  '/apply/$serviceCode/details': typeof ApplyServiceCodeDetailsRoute
  '/apply/$serviceCode/documents': typeof ApplyServiceCodeDocumentsRoute
  '/apply/$serviceCode/review': typeof ApplyServiceCodeReviewRoute
  '/admin': typeof AuthedAdminIndexRoute
  '/requests': typeof AuthedRequestsIndexRoute
  '/apply/$serviceCode': typeof ApplyServiceCodeIndexRoute
  '/service/$serviceCode': typeof AuthedserviceServiceServiceCodeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteRouteWithChildren
  '/accept-invitation': typeof AcceptInvitationRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/requirements': typeof RequirementsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/track': typeof TrackRoute
  '/apply/$serviceCode': typeof ApplyServiceCodeRouteRouteWithChildren
  '/_authed/cashier': typeof AuthedCashierRoute
  '/_authed/dashboard': typeof AuthedDashboardRoute
  '/_authed/my-requests': typeof AuthedMyRequestsRoute
  '/_authed/payment-history': typeof AuthedPaymentHistoryRoute
  '/_authed/staff-dashboard': typeof AuthedStaffDashboardRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/apply/': typeof ApplyIndexRoute
  '/_authed/(service)/services': typeof AuthedserviceServicesRoute
  '/_authed/admin/reports': typeof AuthedAdminReportsRoute
  '/_authed/admin/services': typeof AuthedAdminServicesRoute
  '/_authed/admin/staff': typeof AuthedAdminStaffRoute
  '/_authed/requests/$requestId': typeof AuthedRequestsRequestIdRoute
  '/_authed/system-admin/accounts': typeof AuthedSystemAdminAccountsRoute
  '/_authed/system-admin/audit': typeof AuthedSystemAdminAuditRoute
  '/_authed/system-admin/health': typeof AuthedSystemAdminHealthRoute
  '/_authed/system-admin/security': typeof AuthedSystemAdminSecurityRoute
  '/apply/$serviceCode/case': typeof ApplyServiceCodeCaseRoute
  '/apply/$serviceCode/details': typeof ApplyServiceCodeDetailsRoute
  '/apply/$serviceCode/documents': typeof ApplyServiceCodeDocumentsRoute
  '/apply/$serviceCode/review': typeof ApplyServiceCodeReviewRoute
  '/_authed/admin/': typeof AuthedAdminIndexRoute
  '/_authed/requests/': typeof AuthedRequestsIndexRoute
  '/apply/$serviceCode/': typeof ApplyServiceCodeIndexRoute
  '/_authed/(service)/service/$serviceCode': typeof AuthedserviceServiceServiceCodeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accept-invitation'
    | '/forgot-password'
    | '/login'
    | '/logout'
    | '/requirements'
    | '/reset-password'
    | '/signup'
    | '/track'
    | '/apply/$serviceCode'
    | '/cashier'
    | '/dashboard'
    | '/my-requests'
    | '/payment-history'
    | '/staff-dashboard'
    | '/auth/callback'
    | '/apply/'
    | '/services'
    | '/admin/reports'
    | '/admin/services'
    | '/admin/staff'
    | '/requests/$requestId'
    | '/system-admin/accounts'
    | '/system-admin/audit'
    | '/system-admin/health'
    | '/system-admin/security'
    | '/apply/$serviceCode/case'
    | '/apply/$serviceCode/details'
    | '/apply/$serviceCode/documents'
    | '/apply/$serviceCode/review'
    | '/admin/'
    | '/requests/'
    | '/apply/$serviceCode/'
    | '/service/$serviceCode'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accept-invitation'
    | '/forgot-password'
    | '/login'
    | '/logout'
    | '/requirements'
    | '/reset-password'
    | '/signup'
    | '/track'
    | '/cashier'
    | '/dashboard'
    | '/my-requests'
    | '/payment-history'
    | '/staff-dashboard'
    | '/auth/callback'
    | '/apply'
    | '/services'
    | '/admin/reports'
    | '/admin/services'
    | '/admin/staff'
    | '/requests/$requestId'
    | '/system-admin/accounts'
    | '/system-admin/audit'
    | '/system-admin/health'
    | '/system-admin/security'
    | '/apply/$serviceCode/case'
    | '/apply/$serviceCode/details'
    | '/apply/$serviceCode/documents'
    | '/apply/$serviceCode/review'
    | '/admin'
    | '/requests'
    | '/apply/$serviceCode'
    | '/service/$serviceCode'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/accept-invitation'
    | '/forgot-password'
    | '/login'
    | '/logout'
    | '/requirements'
    | '/reset-password'
    | '/signup'
    | '/track'
    | '/apply/$serviceCode'
    | '/_authed/cashier'
    | '/_authed/dashboard'
    | '/_authed/my-requests'
    | '/_authed/payment-history'
    | '/_authed/staff-dashboard'
    | '/auth/callback'
    | '/apply/'
    | '/_authed/(service)/services'
    | '/_authed/admin/reports'
    | '/_authed/admin/services'
    | '/_authed/admin/staff'
    | '/_authed/requests/$requestId'
    | '/_authed/system-admin/accounts'
    | '/_authed/system-admin/audit'
    | '/_authed/system-admin/health'
    | '/_authed/system-admin/security'
    | '/apply/$serviceCode/case'
    | '/apply/$serviceCode/details'
    | '/apply/$serviceCode/documents'
    | '/apply/$serviceCode/review'
    | '/_authed/admin/'
    | '/_authed/requests/'
    | '/apply/$serviceCode/'
    | '/_authed/(service)/service/$serviceCode'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRouteRoute: typeof AuthedRouteRouteWithChildren
  AcceptInvitationRoute: typeof AcceptInvitationRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  LogoutRoute: typeof LogoutRoute
  RequirementsRoute: typeof RequirementsRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  TrackRoute: typeof TrackRoute
  ApplyServiceCodeRouteRoute: typeof ApplyServiceCodeRouteRouteWithChildren
  AuthCallbackRoute: typeof AuthCallbackRoute
  ApplyIndexRoute: typeof ApplyIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/track': {
      id: '/track'
      path: '/track'
      fullPath: '/track'
      preLoaderRoute: typeof TrackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/requirements': {
      id: '/requirements'
      path: '/requirements'
      fullPath: '/requirements'
      preLoaderRoute: typeof RequirementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accept-invitation': {
      id: '/accept-invitation'
      path: '/accept-invitation'
      fullPath: '/accept-invitation'
      preLoaderRoute: typeof AcceptInvitationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply/': {
      id: '/apply/'
      path: '/apply'
      fullPath: '/apply/'
      preLoaderRoute: typeof ApplyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/staff-dashboard': {
      id: '/_authed/staff-dashboard'
      path: '/staff-dashboard'
      fullPath: '/staff-dashboard'
      preLoaderRoute: typeof AuthedStaffDashboardRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/payment-history': {
      id: '/_authed/payment-history'
      path: '/payment-history'
      fullPath: '/payment-history'
      preLoaderRoute: typeof AuthedPaymentHistoryRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/my-requests': {
      id: '/_authed/my-requests'
      path: '/my-requests'
      fullPath: '/my-requests'
      preLoaderRoute: typeof AuthedMyRequestsRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/dashboard': {
      id: '/_authed/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthedDashboardRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/cashier': {
      id: '/_authed/cashier'
      path: '/cashier'
      fullPath: '/cashier'
      preLoaderRoute: typeof AuthedCashierRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/apply/$serviceCode': {
      id: '/apply/$serviceCode'
      path: '/apply/$serviceCode'
      fullPath: '/apply/$serviceCode'
      preLoaderRoute: typeof ApplyServiceCodeRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply/$serviceCode/': {
      id: '/apply/$serviceCode/'
      path: '/'
      fullPath: '/apply/$serviceCode/'
      preLoaderRoute: typeof ApplyServiceCodeIndexRouteImport
      parentRoute: typeof ApplyServiceCodeRouteRoute
    }
    '/_authed/requests/': {
      id: '/_authed/requests/'
      path: '/requests'
      fullPath: '/requests/'
      preLoaderRoute: typeof AuthedRequestsIndexRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/admin/': {
      id: '/_authed/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthedAdminIndexRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/apply/$serviceCode/review': {
      id: '/apply/$serviceCode/review'
      path: '/review'
      fullPath: '/apply/$serviceCode/review'
      preLoaderRoute: typeof ApplyServiceCodeReviewRouteImport
      parentRoute: typeof ApplyServiceCodeRouteRoute
    }
    '/apply/$serviceCode/documents': {
      id: '/apply/$serviceCode/documents'
      path: '/documents'
      fullPath: '/apply/$serviceCode/documents'
      preLoaderRoute: typeof ApplyServiceCodeDocumentsRouteImport
      parentRoute: typeof ApplyServiceCodeRouteRoute
    }
    '/apply/$serviceCode/details': {
      id: '/apply/$serviceCode/details'
      path: '/details'
      fullPath: '/apply/$serviceCode/details'
      preLoaderRoute: typeof ApplyServiceCodeDetailsRouteImport
      parentRoute: typeof ApplyServiceCodeRouteRoute
    }
    '/apply/$serviceCode/case': {
      id: '/apply/$serviceCode/case'
      path: '/case'
      fullPath: '/apply/$serviceCode/case'
      preLoaderRoute: typeof ApplyServiceCodeCaseRouteImport
      parentRoute: typeof ApplyServiceCodeRouteRoute
    }
    '/_authed/system-admin/security': {
      id: '/_authed/system-admin/security'
      path: '/system-admin/security'
      fullPath: '/system-admin/security'
      preLoaderRoute: typeof AuthedSystemAdminSecurityRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/system-admin/health': {
      id: '/_authed/system-admin/health'
      path: '/system-admin/health'
      fullPath: '/system-admin/health'
      preLoaderRoute: typeof AuthedSystemAdminHealthRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/system-admin/audit': {
      id: '/_authed/system-admin/audit'
      path: '/system-admin/audit'
      fullPath: '/system-admin/audit'
      preLoaderRoute: typeof AuthedSystemAdminAuditRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/system-admin/accounts': {
      id: '/_authed/system-admin/accounts'
      path: '/system-admin/accounts'
      fullPath: '/system-admin/accounts'
      preLoaderRoute: typeof AuthedSystemAdminAccountsRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/requests/$requestId': {
      id: '/_authed/requests/$requestId'
      path: '/requests/$requestId'
      fullPath: '/requests/$requestId'
      preLoaderRoute: typeof AuthedRequestsRequestIdRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/admin/staff': {
      id: '/_authed/admin/staff'
      path: '/admin/staff'
      fullPath: '/admin/staff'
      preLoaderRoute: typeof AuthedAdminStaffRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/admin/services': {
      id: '/_authed/admin/services'
      path: '/admin/services'
      fullPath: '/admin/services'
      preLoaderRoute: typeof AuthedAdminServicesRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/admin/reports': {
      id: '/_authed/admin/reports'
      path: '/admin/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AuthedAdminReportsRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/(service)/services': {
      id: '/_authed/(service)/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof AuthedserviceServicesRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/(service)/service/$serviceCode': {
      id: '/_authed/(service)/service/$serviceCode'
      path: '/service/$serviceCode'
      fullPath: '/service/$serviceCode'
      preLoaderRoute: typeof AuthedserviceServiceServiceCodeRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
  }
}

interface AuthedRouteRouteChildren {
  AuthedCashierRoute: typeof AuthedCashierRoute
  AuthedDashboardRoute: typeof AuthedDashboardRoute
  AuthedMyRequestsRoute: typeof AuthedMyRequestsRoute
  AuthedPaymentHistoryRoute: typeof AuthedPaymentHistoryRoute
  AuthedStaffDashboardRoute: typeof AuthedStaffDashboardRoute
  AuthedserviceServicesRoute: typeof AuthedserviceServicesRoute
  AuthedAdminReportsRoute: typeof AuthedAdminReportsRoute
  AuthedAdminServicesRoute: typeof AuthedAdminServicesRoute
  AuthedAdminStaffRoute: typeof AuthedAdminStaffRoute
  AuthedRequestsRequestIdRoute: typeof AuthedRequestsRequestIdRoute
  AuthedSystemAdminAccountsRoute: typeof AuthedSystemAdminAccountsRoute
  AuthedSystemAdminAuditRoute: typeof AuthedSystemAdminAuditRoute
  AuthedSystemAdminHealthRoute: typeof AuthedSystemAdminHealthRoute
  AuthedSystemAdminSecurityRoute: typeof AuthedSystemAdminSecurityRoute
  AuthedAdminIndexRoute: typeof AuthedAdminIndexRoute
  AuthedRequestsIndexRoute: typeof AuthedRequestsIndexRoute
  AuthedserviceServiceServiceCodeRoute: typeof AuthedserviceServiceServiceCodeRoute
}

const AuthedRouteRouteChildren: AuthedRouteRouteChildren = {
  AuthedCashierRoute: AuthedCashierRoute,
  AuthedDashboardRoute: AuthedDashboardRoute,
  AuthedMyRequestsRoute: AuthedMyRequestsRoute,
  AuthedPaymentHistoryRoute: AuthedPaymentHistoryRoute,
  AuthedStaffDashboardRoute: AuthedStaffDashboardRoute,
  AuthedserviceServicesRoute: AuthedserviceServicesRoute,
  AuthedAdminReportsRoute: AuthedAdminReportsRoute,
  AuthedAdminServicesRoute: AuthedAdminServicesRoute,
  AuthedAdminStaffRoute: AuthedAdminStaffRoute,
  AuthedRequestsRequestIdRoute: AuthedRequestsRequestIdRoute,
  AuthedSystemAdminAccountsRoute: AuthedSystemAdminAccountsRoute,
  AuthedSystemAdminAuditRoute: AuthedSystemAdminAuditRoute,
  AuthedSystemAdminHealthRoute: AuthedSystemAdminHealthRoute,
  AuthedSystemAdminSecurityRoute: AuthedSystemAdminSecurityRoute,
  AuthedAdminIndexRoute: AuthedAdminIndexRoute,
  AuthedRequestsIndexRoute: AuthedRequestsIndexRoute,
  AuthedserviceServiceServiceCodeRoute: AuthedserviceServiceServiceCodeRoute,
}

const AuthedRouteRouteWithChildren = AuthedRouteRoute._addFileChildren(
  AuthedRouteRouteChildren,
)

interface ApplyServiceCodeRouteRouteChildren {
  ApplyServiceCodeCaseRoute: typeof ApplyServiceCodeCaseRoute
  ApplyServiceCodeDetailsRoute: typeof ApplyServiceCodeDetailsRoute
  ApplyServiceCodeDocumentsRoute: typeof ApplyServiceCodeDocumentsRoute
  ApplyServiceCodeReviewRoute: typeof ApplyServiceCodeReviewRoute
  ApplyServiceCodeIndexRoute: typeof ApplyServiceCodeIndexRoute
}

const ApplyServiceCodeRouteRouteChildren: ApplyServiceCodeRouteRouteChildren = {
  ApplyServiceCodeCaseRoute: ApplyServiceCodeCaseRoute,
  ApplyServiceCodeDetailsRoute: ApplyServiceCodeDetailsRoute,
  ApplyServiceCodeDocumentsRoute: ApplyServiceCodeDocumentsRoute,
  ApplyServiceCodeReviewRoute: ApplyServiceCodeReviewRoute,
  ApplyServiceCodeIndexRoute: ApplyServiceCodeIndexRoute,
}

const ApplyServiceCodeRouteRouteWithChildren =
  ApplyServiceCodeRouteRoute._addFileChildren(
    ApplyServiceCodeRouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRouteRoute: AuthedRouteRouteWithChildren,
  AcceptInvitationRoute: AcceptInvitationRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  LogoutRoute: LogoutRoute,
  RequirementsRoute: RequirementsRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  TrackRoute: TrackRoute,
  ApplyServiceCodeRouteRoute: ApplyServiceCodeRouteRouteWithChildren,
  AuthCallbackRoute: AuthCallbackRoute,
  ApplyIndexRoute: ApplyIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
