-- Privacy-safe operational telemetry for the System Health Dashboard.
-- These tables must never contain request bodies, citizen form data, document
-- names/paths, authentication tokens, or other protected case content.

create table if not exists public.system_health_snapshots (
  id bigint generated by default as identity primary key,
  component_key text not null check (component_key in ('database', 'authentication', 'storage')),
  status text not null check (status in ('operational', 'degraded', 'outage', 'unknown')),
  response_time_ms integer check (response_time_ms is null or response_time_ms >= 0),
  recorded_at timestamptz not null default now()
);

create index if not exists system_health_snapshots_component_recorded_idx
  on public.system_health_snapshots(component_key, recorded_at desc);

create table if not exists public.system_operational_events (
  id uuid primary key default gen_random_uuid(),
  component_key text not null,
  severity text not null check (severity in ('info', 'warning', 'critical')),
  event_type text not null check (event_type in ('degradation', 'recovery', 'maintenance')),
  title text not null check (length(title) between 1 and 120),
  summary text not null default '' check (length(summary) <= 500),
  started_at timestamptz not null default now(),
  resolved_at timestamptz,
  related_audit_event_id uuid references public.system_audit_events(id) on delete set null,
  created_at timestamptz not null default now(),
  constraint system_operational_events_resolution_check
    check (resolved_at is null or resolved_at >= started_at)
);

comment on column public.system_operational_events.summary is
  'Redacted operational summary only. Citizen submissions and document metadata are prohibited.';

create index if not exists system_operational_events_started_idx
  on public.system_operational_events(started_at desc);
create index if not exists system_operational_events_active_idx
  on public.system_operational_events(resolved_at) where resolved_at is null;

create table if not exists public.system_background_job_runs (
  id bigint generated by default as identity primary key,
  job_key text not null,
  status text not null check (status in ('running', 'succeeded', 'failed', 'cancelled')),
  failure_code text check (failure_code is null or length(failure_code) <= 80),
  retry_count integer not null default 0 check (retry_count >= 0),
  started_at timestamptz not null default now(),
  completed_at timestamptz,
  constraint system_background_job_runs_completion_check
    check (completed_at is null or completed_at >= started_at)
);

comment on table public.system_background_job_runs is
  'Metadata-only job telemetry. Job payloads and citizen identifiers are prohibited.';

create index if not exists system_background_job_runs_started_idx
  on public.system_background_job_runs(started_at desc);
create index if not exists system_background_job_runs_status_idx
  on public.system_background_job_runs(status, started_at desc);

alter table public.system_health_snapshots enable row level security;
alter table public.system_operational_events enable row level security;
alter table public.system_background_job_runs enable row level security;

grant select on public.system_health_snapshots to authenticated;
grant select on public.system_operational_events to authenticated;
grant select on public.system_background_job_runs to authenticated;
grant all on public.system_health_snapshots to service_role;
grant all on public.system_operational_events to service_role;
grant all on public.system_background_job_runs to service_role;
grant usage, select on sequence public.system_health_snapshots_id_seq to service_role;
grant usage, select on sequence public.system_background_job_runs_id_seq to service_role;

revoke insert, update, delete, truncate on public.system_health_snapshots from authenticated, anon;
revoke insert, update, delete, truncate on public.system_operational_events from authenticated, anon;
revoke insert, update, delete, truncate on public.system_background_job_runs from authenticated, anon;

create or replace function public.is_active_system_administrator()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.profiles p
    where p.id = auth.uid()
      and p.role::text = 'system_admin'
      and p.access_status = 'active'
  );
$$;

revoke all on function public.is_active_system_administrator() from public, anon;
grant execute on function public.is_active_system_administrator() to authenticated;

drop policy if exists "System administrators can read health snapshots" on public.system_health_snapshots;
create policy "System administrators can read health snapshots"
  on public.system_health_snapshots for select to authenticated
  using (public.is_active_system_administrator());

drop policy if exists "System administrators can read operational events" on public.system_operational_events;
create policy "System administrators can read operational events"
  on public.system_operational_events for select to authenticated
  using (public.is_active_system_administrator());

drop policy if exists "System administrators can read job telemetry" on public.system_background_job_runs;
create policy "System administrators can read job telemetry"
  on public.system_background_job_runs for select to authenticated
  using (public.is_active_system_administrator());

-- Service-role-only aggregate. It deliberately exposes only object count and
-- total bytes, never object names, paths, owners, or document metadata.
create or replace function public.system_health_storage_usage()
returns table (object_count bigint, total_bytes bigint)
language sql
stable
security definer
set search_path = public, storage
as $$
  select
    count(*)::bigint,
    coalesce(sum(
      case
        when (metadata ->> 'size') ~ '^[0-9]+$'
          then (metadata ->> 'size')::bigint
        else 0
      end
    ), 0)::bigint
  from storage.objects
  where bucket_id = 'request-documents';
$$;

revoke all on function public.system_health_storage_usage() from public, anon, authenticated;
grant execute on function public.system_health_storage_usage() to service_role;
